### ISSUE TITLE
Size of month buttons

### ISSUE THREAD

**Issue by herbertamukhuma** [zulfahmi93/dart_libpray#12]
![image](https://user-images.githubusercontent.com/37830837/227239304-94164da8-dc37-4d97-80c7-24d64a64c86f.png)
Provide a way of controlling the size of the month button or fit them within the available space

**Comment by srikalaVanga** [comment]
apply  padding for gridview

**Comment by hoangdangduy** [comment]
I same have an issue on Android simulator Pixel 6 Api 33 (1080*2400)

```
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  intl: ^0.18.0
  month_year_picker: ^0.3.0+1
```


![Screenshot from 2023-06-07 00-45-04](https://github.com/zulfahmi93/dart-libpray/assets/8912039/8f2c74d7-6e72-41f0-aaa2-fe01ff5d585d)
